# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Factorialsucks < Formula
  desc "FactorialHR auto clock in for the whole month from the command line."
  homepage "https://github.com/alejoar/factorialsucks/"
  version "2.0.2"
  license "MIT"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/alejoar/factorialsucks/releases/download/v2.0.2/factorialsucks_2.0.2_Darwin_arm64.tar.gz"
      sha256 "c9ee64acbc6310de68cce3db63b6c98705ee4868a457b08adb047281b20149a9"

      def install
        bin.install "factorialsucks"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/alejoar/factorialsucks/releases/download/v2.0.2/factorialsucks_2.0.2_Darwin_x86_64.tar.gz"
      sha256 "2523d97d20698de4e605d1a6168ff75b82e0d4b2ee72939dbbae3526784951a7"

      def install
        bin.install "factorialsucks"
      end
    end
  end

  on_linux do
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/alejoar/factorialsucks/releases/download/v2.0.2/factorialsucks_2.0.2_Linux_arm64.tar.gz"
      sha256 "ddcbf5332c631f5ee713437aebc9915227ac2ea114b71160deea4c469f0e422e"

      def install
        bin.install "factorialsucks"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/alejoar/factorialsucks/releases/download/v2.0.2/factorialsucks_2.0.2_Linux_x86_64.tar.gz"
      sha256 "a47eb91cc0a8cbcb9074e088a22c93cf3b3cfd02290e8bb3a0020fd0e33ddf98"

      def install
        bin.install "factorialsucks"
      end
    end
  end
end
