# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Factorialsucks < Formula
  desc "FactorialHR auto clock in for the whole month from the command line."
  homepage "https://github.com/alejoar/factorialsucks/"
  version "2.0"
  license "MIT"
  bottle :unneeded

  if OS.mac? && Hardware::CPU.intel?
    url "https://github.com/alejoar/factorialsucks/releases/download/v2.0/factorialsucks_2.0_Darwin_x86_64.tar.gz"
    sha256 "a3f676471708f82bae09e7d910386c295d3d2871afcdd05f9646ac6dc646a677"
  end
  if OS.linux? && Hardware::CPU.intel?
    url "https://github.com/alejoar/factorialsucks/releases/download/v2.0/factorialsucks_2.0_Linux_x86_64.tar.gz"
    sha256 "a71e6dd60aeb880414fc3621b3c4de13c9b9e394e1f52d01089ef368df240db3"
  end
  if OS.linux? && Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
    url "https://github.com/alejoar/factorialsucks/releases/download/v2.0/factorialsucks_2.0_Linux_arm64.tar.gz"
    sha256 "c368ea90506656ce3c875967778122e4a67c9579b7f44a5ddc230dea047309e1"
  end

  def install
    bin.install "factorialsucks"
  end
end
